version: '3.9'

services:

  pinp-backend:
    image: backend:dev
    build: .
    container_name: pinp-backend
    ports:
      - 8080:8080
    networks:
      - pinp-backend-net

networks:
  pinp-backend-net:
