name: Continuous Delivery

on:
  pull_request: 
    branches: 
      - master
    types:
      - closed

jobs:
  build-push-deploy:
    if: github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build and push image
        uses: aevea/action-kaniko@master
        with:
          build_file: Dockerfile-rpi
          image: ${{ secrets.DOCKERHUB_USER }}/pinp
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}
          cache: true
          cache_registry: ${{ secrets.DOCKERHUB_USER }}/cache

      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
