name: Build and Push Dockerfile-rpi

on:
  push: 
    branches: [ master, issue-83-fix_image_publishing ]

jobs:
  login-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWD: ${{ secrets.DOCKERHUB_PASSWD }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWD
    
    - uses: aevea/action-kaniko@v0.6.0

    - name: Build the Docker image  
      with:
        image: mistagreen/pinp
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWD }}
        cache: true
        cache_registry: mistagreen/cache
        tag: $GITHUB_SHA 
      
    - name: Push the Docker image
      run: docker push mistagreen/pinp
  # push-to-dockerhub:
  #   runs-on: ubuntu-latest

  #   steps:
    