name: Build and Push Dockerfile-rpi

on:
  push: 
    branches: [ master ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASSWD: ${{ secrets.DOCKERHUB_PASSWD }}
      run: |
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWD
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile-rpi --tag mistagreen/pinp:$GITHUB_SHA
      
    - name: Docker Push
      run: docker push mistagreen/pinp